#!/usr/bin/env python3
"""
seed/seed_data.py
=================
Populates the iGaming Anti-Fraud Platform database with:
  - 1 admin user  (login: admin / password: admin123)
  - 40 realistic players generated by Faker
  - 3 multi-account clusters (shared device + IP) for graph testing
  - Sample transactions per player

Usage (after `docker-compose up -d`):
  docker-compose exec backend python /app/../seed/seed_data.py

  -- OR locally --
  pip install asyncpg sqlalchemy[asyncio] passlib[bcrypt] faker
  DATABASE_URL=postgresql+asyncpg://fraud:fraud123@localhost:5432/frauddb python seed/seed_data.py
"""

import asyncio
import os
import random
import uuid
from datetime import datetime, timedelta

from faker import Faker
from passlib.context import CryptContext
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select

# ── Config ────────────────────────────────────────────────────────────────────

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://fraud:fraud123@localhost:5432/frauddb",
)

fake = Faker()
pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")

COUNTRIES = ["LV", "EE", "LT", "FI", "DE", "GB", "UA", "CY", "PL", "SE"]
STATUSES = ["active", "active", "active", "suspended", "banned"]
PAYMENT_METHODS = ["card", "crypto", "bank", "ewallet", "prepaid"]

# ── Shared-attribute pools (for multi-account clusters) ──────────────────────

CLUSTER_IPS = [fake.ipv4() for _ in range(3)]
CLUSTER_DEVICES = [str(uuid.uuid4())[:8] for _ in range(3)]

# ── Helpers ───────────────────────────────────────────────────────────────────

def rand_date(days_ago: int) -> datetime:
    return datetime.utcnow() - timedelta(days=random.randint(0, days_ago))


def make_player(
    cluster_ip: str | None = None,
    cluster_device: str | None = None,
    risk_boost: int = 0,
) -> dict:
    return {
        "id": str(uuid.uuid4()),
        "username": fake.user_name() + str(random.randint(10, 999)),
        "email": fake.email(),
        "full_name": fake.name(),
        "country": random.choice(COUNTRIES),
        "status": random.choice(STATUSES),
        "risk_score": min(100, random.randint(5, 55) + risk_boost),
        "total_deposits": round(random.uniform(50, 15000), 2),
        "total_withdrawals": round(random.uniform(0, 8000), 2),
        "registration_date": rand_date(365),
        "last_login": rand_date(30),
        "last_ip": cluster_ip or fake.ipv4(),
        "registration_ip": cluster_ip or fake.ipv4(),
        "device_fingerprint": cluster_device or str(uuid.uuid4())[:8],
        "flags": [],
        "is_vip": random.random() < 0.1,
        "preferred_payment": random.choice(PAYMENT_METHODS),
        "currency": "EUR",
        "kyc_status": random.choice(["verified", "pending", "rejected"]),
    }


async def run():
    engine = create_async_engine(DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    # Import models AFTER engine creation so they load correctly
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))
    from app.models.player import Player
    from app.models.user import User, UserRole
    from app.models.transaction import Transaction
    from app.core.database import Base

    # Create tables if they don't exist
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:

        # ── 1. Admin user ─────────────────────────────────────────────────────
        existing_admin = await session.execute(
            select(User).where(User.username == "admin")
        )
        if not existing_admin.scalar():
            admin = User(
                id=str(uuid.uuid4()),
                username="admin",
                email="admin@antifraud.local",
                full_name="Platform Administrator",
                hashed_password=pwd_ctx.hash("admin123"),
                role=UserRole.admin,
                is_active=True,
            )
            session.add(admin)
            print("[+] Admin user created  ->  admin / admin123")
        else:
            print("[=] Admin user already exists")

        # ── 2. Regular players (30 standalone) ───────────────────────────────
        standalone_players = [make_player() for _ in range(30)]

        # ── 3. Multi-account clusters (3 clusters x 4 players each) ──────────
        #
        #  Cluster 0: 4 accounts share the same device fingerprint
        #  Cluster 1: 4 accounts share the same IP address
        #  Cluster 2: 4 accounts share BOTH device + IP (highest risk cluster)
        #
        cluster_players = []

        # Cluster 0 — shared device
        for _ in range(4):
            cluster_players.append(
                make_player(cluster_device=CLUSTER_DEVICES[0], risk_boost=30)
            )

        # Cluster 1 — shared IP
        for _ in range(4):
            cluster_players.append(
                make_player(cluster_ip=CLUSTER_IPS[1], risk_boost=25)
            )

        # Cluster 2 — shared device AND IP (most suspicious)
        for _ in range(4):
            cluster_players.append(
                make_player(
                    cluster_ip=CLUSTER_IPS[2],
                    cluster_device=CLUSTER_DEVICES[2],
                    risk_boost=50,
                )
            )

        # Commit all players
        all_players_data = standalone_players + cluster_players
        player_ids = []
        for p_data in all_players_data:
            player = Player(**p_data)
            session.add(player)
            player_ids.append(p_data["id"])

        await session.flush()
        print(f"[+] {len(all_players_data)} players created ({len(standalone_players)} standalone + {len(cluster_players)} in 3 clusters)")
        print(f"    Cluster 0 (shared device {CLUSTER_DEVICES[0]}): 4 players")
        print(f"    Cluster 1 (shared IP    {CLUSTER_IPS[1]}): 4 players")
        print(f"    Cluster 2 (shared IP+device {CLUSTER_IPS[2]} / {CLUSTER_DEVICES[2]}): 4 players")

        # ── 4. Sample transactions ────────────────────────────────────────────
        tx_count = 0
        for pid in player_ids:
            n_tx = random.randint(2, 8)
            for _ in range(n_tx):
                tx = Transaction(
                    id=str(uuid.uuid4()),
                    player_id=pid,
                    amount=round(random.uniform(10, 2000), 2),
                    currency="EUR",
                    type=random.choice(["deposit", "withdrawal"]),
                    status=random.choice(["completed", "pending", "failed"]),
                    payment_method=random.choice(PAYMENT_METHODS),
                    ip_address=fake.ipv4(),
                    device_fingerprint=str(uuid.uuid4())[:8],
                    created_at=rand_date(180),
                    risk_score=random.randint(0, 100),
                    flags=[],
                )
                session.add(tx)
                tx_count += 1

        await session.commit()
        print(f"[+] {tx_count} sample transactions created")
        print("\n=== Seed complete ===")
        print("  Login URL:  http://localhost:5173")
        print("  Credentials: admin / admin123")
        print("  API docs:   http://localhost:8000/docs")


if __name__ == "__main__":
    asyncio.run(run())
